# Generated by Django 4.2.3 on 2023-07-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_collection_product_collection'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_e6a359_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
