# Generated by Django 4.2.3 on 2023-07-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='memebrship',
            new_name='membership',
        ),
    ]
