# Generated by Django 4.2.3 on 2023-07-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_cart_carts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carts',
            new_name='Cart',
        ),
    ]
