# Generated by Django 4.2.3 on 2023-07-27 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
