# Generated by Django 4.2.3 on 2023-07-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cartitem_cart_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
