# Generated by Django 4.2.4 on 2023-08-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
